version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  timetable:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        DATABASE_URL: jdbc:postgresql://postgres:5432/db
        DATABASE_USER: user
        DATABASE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
        - postgres
