name: Continuous Integration

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
  build:
    name: Program build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile the project
        run: |
          mvn clean compile

  analysis:
    name: Code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkstyle
        uses: ./.github/workflows/run_checkstyle.yml

      - name: Tests
        uses: ./.github/workflows/run_tests.yml

  review:
    name: Code review
    runs-on: ubuntu-latest
    needs: [build, analysis]
    steps:
      - name: Await manual approval before merging
        run: echo "Manual review required for merging."