name: Deploy to Production

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DIGITALOCEAN_SSH_KEY:
        required: true
      DOCR_PASSWORD:
        required: true
      DOCR_REGISTRY:
        required: true
      DOCR_USERNAME:
        required: true
jobs:
  deploy-production:
    uses: ./.github/workflows/deploy.yml
    with:
      droplet_ip: '159.89.17.208'
      droplet_url: 'http://timatable.tech'

    secrets:
      DIGITALOCEAN_SSH_KEY: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
      DOCR_PASSWORD: ${{ secrets.DOCR_PASSWORD }}
      DOCR_REGISTRY: ${{ secrets.DOCR_REGISTRY }}
      DOCR_USERNAME: ${{ secrets.DOCR_USERNAME }}