name: Deploy to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-stage:
    uses: ./.github/workflows/deploy.yml
    with:
      droplet_ip: '165.227.133.120'  # Staging Droplet IP
      droplet_url: 'http://stage.timatable.tech'  # Staging URL
