name: Infer Analysis

on:
  workflow_dispatch:

jobs:
  infer:
    runs-on: ubuntu-latest

    steps:
    # Krok 1: Sprawdzenie kodu z repozytorium
    - name: Checkout repository
      uses: actions/checkout@v4

    # Krok 3: Ustawienie JDK (jeśli projekt w Javie)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    # Krok 3: Instalacja Infer, jeśli nie jest zainstalowany
    - name: Install Infer
      run: |
        if ! command -v infer &> /dev/null; then
          echo "Infer not found, installing..."
          wget "https://github.com/facebook/infer/releases/download/v1.2.0/infer-linux-x86_64-v1.2.0.tar.xz" -P /opt && \
          sudo tar -C /opt -xJv -f "/opt/infer-linux-x86_64-v1.2.0.tar.xz" && \
          sudo ln -s "/opt/infer-linux-x86_64-v1.2.0/bin/infer" /usr/local/bin/infer
        else
          echo "Infer is already installed."
        fi

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run Infer
      run: |
        infer run -- mvn clean package

    # Krok 6: (Opcjonalnie) Pobieranie wyników analizy Infer
    - name: Upload Infer Report
      uses: actions/upload-artifact@v4
      with:
        name: infer-report
        path: infer-out/report.json  # Infer domyślnie zapisuje wyniki w folderze infer-out
