name: Forbidden apis

on:
  workflow_dispatch:

jobs:
  ck-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Cache forbidden-apis library
      uses: actions/cache@v4
      id: cache-forbidden-apis
      with:
        path: forbidden-apis
        key: ${{ runner.os }}-forbidden-apis-${{ hashFiles('forbiddenapis-3.8.jar') }}

    - name: Download forbidden-apis from Maven repo
      if: steps.cache-forbidden-apis.outputs.cache-hit != 'true'
      run: |
        wget https://repo1.maven.org/maven2/de/thetaphi/forbiddenapis/3.8/forbiddenapis-3.8.jar     

    - name: Run forbidden-apis analysis
      run: |
        mkdir forbidden-apis_metrics
        mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt
        CLASSPATH=$(cat classpath.txt)
        cat classpath.txt
        java -jar forbiddenapis-3.8.jar --dir target/classes -cp ${CLASSPATH}:target/classes -b jdk-unsafe-17 --ignoresignaturesofmissingclasses 
        ls -la