name: Analysis RefactorFirst

on:
  workflow_dispatch:

jobs:
  run-refactorfirst:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Run RefactorFirst
      run: |
        mvn -B clean test \
        org.hjug.refactorfirst.plugin:refactor-first-maven-plugin:0.6.1:htmlReport \
        && echo "$(cat target/site/refactor-first-report.html)" >> $GITHUB_STEP_SUMMARY        

    - name: Upload RefactorFirst Report
      uses: actions/upload-artifact@v4
      with:
        name: RefactorFirst-report
        path: target/site/refactor-first-report.html
