name: CK Metrics

on:
  workflow_dispatch:

jobs:
  ck-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Cache CK library
      uses: actions/cache@v4
      id: cache-ck
      with:
        path: ck
        key: ${{ runner.os }}-ck-${{ hashFiles('ck/pom.xml') }}

    - name: Build CK from source
      if: steps.cache-ck.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/mauricioaniche/ck.git
        cd ck
        mvn clean compile package

    - name: Run CK analysis
      run: |
        mkdir ck_metrics
        java -jar ck/target/ck-0.7.1-SNAPSHOT-jar-with-dependencies.jar src/main false 0 true ck_metrics/

    - name: Upload CK Metrics Results
      uses: actions/upload-artifact@v4
      with:
        name: ck-metrics-results
        path: ck_metrics/