name: Error Prone

on:
  workflow_dispatch:

jobs:
  ck-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Error Prone library
      uses: actions/cache@v4
      id: cache-error_prone
      with:
        path: error_prone_core-2.33.0.jar
        key: ${{ runner.os }}-error_prone-${{ hashFiles('error_prone_core-2.33.0.jar') }}

    - name: Download Error Prone from Maven repo
      if: steps.cache-error_prone.outputs.cache-hit != 'true'
      run: |
        wget https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.33.0/error_prone_core-2.33.0.jar
      
    
