name: DesigniteJava

on:
  workflow_dispatch:

jobs:
  ck-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache DesigniteJava library
      uses: actions/cache@v4
      id: cache-DesigniteJava
      with:
        path: DesigniteJava
        key: ${{ runner.os }}-DesigniteJava-${{ hashFiles('DesigniteJava/pom.xml') }}

    - name: Build DesigniteJava from source
      if: steps.cache-DesigniteJava.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/tushartushar/DesigniteJava.git
        cd DesigniteJava
        mvn clean install

    - name: Run DesigniteJava analysis
      run: |
        mkdir DesigniteJava_metrics
        
        java -jar DesigniteJava/target/DesigniteJava.jar -i src/main -o DesigniteJava_metrics

    - name: Upload DesigniteJava Metrics Results
      uses: actions/upload-artifact@v4
      with:
        name: DesigniteJava-metrics-results
        path: DesigniteJava_metrics/