name: Analysis PMD

on:
  workflow_dispatch:
  workflow_call: {}

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: '7.7.0'
          sourcePath: 'src/main/java'
          rulesets: 'category/java/bestpractices.xml,
                      category/java/codestyle.xml,
                      category/java/design.xml,
                      category/java/documentation.xml,
                      category/java/errorprone.xml,
                      category/java/multithreading.xml,
                      category/java/performance.xml,
                      category/java/security.xml'
          analyzeModifiedFilesOnly: false

      - name: Verify PMD Report
        if: steps.pmd.outputs.violations != 0
        run: |
          echo ${{ steps.pmd.outputs.violations }} violations found by PMD
          exit 1